[package]
name = "launchpad"
version = "0.1.0"
description = "No-code DEX token launchpad"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "launchpad"

[dependencies]
anchor-lang = "0.25.0"
anchor-spl = "0.25.0"
solana-program = "~1.14.0"
